nome = str(input("Digite o seu nome: "))
nota1 = int(input("Digite a sua primeira nota: "))
nota2 = int(input("Digite a sua segunda nota: "))
media = ((nota1 + nota2) / 2)
print(nome,", a sua média é:", media)
